name: sws-ter-legacy
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.6
  - pip
  - pip:
      - mmcv-full==1.7.1
      - -r requirements/runtime.txt
      - -e .
